include ../../TI_Build.make

export PATH := $(TI_uclibc_path):$(shell echo -n $(PATH))

all: build install

build:
	$(MAKE) 
	mips_fp_le-strip -s -R .note msntp

install:
	install -m 0755 -d $(TARGET_HOME)/$(TI_rsbindir) 
	install -m 0755 msntp $(TARGET_HOME)/$(TI_rsbindir)/msntp

clean:
	$(MAKE) -i  clean
