include ../../TI_Build.make

export PATH := $(TI_uclibc_path):$(shell echo -n $(PATH))
export CROSS_COMPILE_PREFIX=$(TI_uclibc_base)

all: build install

build:
	CFLAGS="-Os -Wall -W -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Winline" 
	$(MAKE)

install:
	install -m 0755 IGMPProxy $(TARGET_HOME)$(TI_sbindir)/IGMPProxy

clean:
	$(MAKE) clean
