include ../../TI_Build.make

export PATH := $(TI_uclibc_path):$(shell echo -n $(PATH))
export CROSS_COMPILE_PREFIX=$(TI_uclibc_base)

all: build install

build:
	$(MAKE) KERNEL_DIR=$(TI_Kernel_path)/$(TI_kernel_version)
#	strip -s ledapp

install:
	install -m 0755 ledapp $(TARGET_HOME)$(TI_rsbindir)/ledapp

clean:
	$(MAKE) clean
