
all: build install

build:
	ln -sf ../kernel/linux-2.4.17_mvl21/include include
	$(MAKE) LDFLAGS="-L../../tools/lib -lztemp"


install: 
	install -m 0755 mkcramfs ../../tools/bin


clean:
	rm -f ../../tools/bin/mkcramfs
	$(MAKE) clean
